apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: samplepythonapp
  name: samplepythonapp 
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 31500
    protocol: TCP
    targetPort: 3000
  selector:
    app: samplepythonapp
status:
  loadBalancer: {}